/**
 * CoachPage.tsx — Pre-writing ritual.
 *
 * Guided 3-question conversation before the user starts writing.
 * Questions are generated by the letter-coach Edge Function and revealed
 * character-by-character (typewriter style).
 *
 * Flow:
 *   Q1 → (answer) → Q2 → (answer) → Q3 → (answer) → intent summary
 *   → "Begin Writing" navigates to /compose with session context.
 *   "Skip" at any point navigates to /compose without a session.
 *
 * Route: /coach  (protected)
 */

import { useState, useEffect, useRef, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '../lib/supabaseClient';
import '../styles/global.css';
import '../styles/coach.css';

type Phase = 'loading' | 'question' | 'answering' | 'next-loading' | 'summary' | 'error';

interface QAPair {
  question: string;
  answer:   string;
}

// ---- Typewriter reveal hook ------------------------------------

function useTypewriterReveal(text: string, onDone?: () => void) {
  const [displayed, setDisplayed] = useState('');
  const [done,      setDone]      = useState(false);

  useEffect(() => {
    if (!text) return;
    setDisplayed('');
    setDone(false);

    let i = 0;
    // Vary speed slightly for a natural feel
    const BASE_SPEED = 28;

    const tick = () => {
      i++;
      setDisplayed(text.slice(0, i));
      if (i >= text.length) {
        setDone(true);
        onDone?.();
      } else {
        const jitter  = Math.random() * 20 - 10; // ±10ms
        const delay   = BASE_SPEED + jitter;
        timerId.current = window.setTimeout(tick, delay);
      }
    };

    const timerId = { current: 0 as number };
    timerId.current = window.setTimeout(tick, BASE_SPEED);

    return () => window.clearTimeout(timerId.current);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [text]);

  return { displayed, done };
}

// ---- Component -------------------------------------------------

export function CoachPage() {
  const navigate = useNavigate();

  const [phase,          setPhase]          = useState<Phase>('loading');
  const [questionNumber, setQuestionNumber] = useState(1);
  const [currentQuestion,setCurrentQuestion]= useState('');
  const [currentAnswer,  setCurrentAnswer]  = useState('');
  const [pairs,          setPairs]          = useState<QAPair[]>([]);
  const [sessionId,      setSessionId]      = useState<string | null>(null);
  const [intentSummary,  setIntentSummary]  = useState('');
  const [suggestion,     setSuggestion]     = useState('');
  const [apiError,       setApiError]       = useState('');

  const answerRef = useRef<HTMLTextAreaElement>(null);

  // Typewriter state for question and summary
  const questionReveal = useTypewriterReveal(
    phase === 'question' || phase === 'answering' ? currentQuestion : '',
    () => setPhase('answering')
  );
  const summaryReveal  = useTypewriterReveal(
    phase === 'summary' ? intentSummary : ''
  );
  const suggestReveal  = useTypewriterReveal(
    phase === 'summary' && summaryReveal.done ? suggestion : ''
  );

  // ---- API helpers -----------------------------------------------

  const callCoach = useCallback(async (body: Record<string, unknown>) => {
    const { data, error } = await supabase.functions.invoke('letter-coach', { body });
    if (error) {
      // Extract the real error message from the response body when available
      let detail = error.message;
      try {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const ctx = (error as any).context as Response | undefined;
        if (ctx) {
          const json = await ctx.json().catch(() => null);
          if (json?.error) detail = json.error;
        }
      } catch { /* keep original */ }
      throw new Error(detail);
    }
    return data;
  }, []);

  // ---- Load first question on mount ------------------------------

  useEffect(() => {
    document.title = 'Before You Write — Inkwell';

    callCoach({ step: 'question', questionNumber: 1, previousAnswers: [] })
      .then((data) => {
        setCurrentQuestion(data.question);
        setSessionId(data.sessionId ?? null);
        setPhase('question');
      })
      .catch((err) => {
        console.error('[coach] error:', err);
        const msg = err?.message ?? String(err);
        setApiError(`Coach unavailable (${msg}). You can still write — just skip.`);
        setPhase('error');
      });
  // Only on mount
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Focus textarea once we enter the answering phase
  useEffect(() => {
    if (phase === 'answering') {
      answerRef.current?.focus();
    }
  }, [phase]);

  // ---- Submit answer ---------------------------------------------

  const handleContinue = useCallback(async () => {
    const trimmed = currentAnswer.trim();
    if (!trimmed) return;

    const newPair: QAPair = { question: currentQuestion, answer: trimmed };
    const newPairs        = [...pairs, newPair];
    setPairs(newPairs);
    setCurrentAnswer('');

    if (questionNumber < 3) {
      // Fetch next question
      setPhase('next-loading');
      const nextQ = questionNumber + 1 as 1 | 2 | 3;

      try {
        const data = await callCoach({
          step:            'question',
          questionNumber:  nextQ,
          previousAnswers: newPairs,
          sessionId,
        });
        setQuestionNumber(nextQ);
        setCurrentQuestion(data.question);
        setPhase('question');
      } catch (err) {
        console.error('[coach]', err);
        setApiError('Something went wrong. You can skip ahead and start writing.');
        setPhase('error');
      }
    } else {
      // Fetch summary after Q3
      setPhase('next-loading');

      try {
        const data = await callCoach({
          step:      'summary',
          sessionId,
          answers:   newPairs,
        });
        setIntentSummary(data.intentSummary ?? '');
        setSuggestion(data.structureSuggestion ?? '');
        setPhase('summary');
      } catch (err) {
        console.error('[coach]', err);
        // Graceful fallback: skip to compose with whatever we have
        navigate('/compose', {
          state: { sessionId, intentSummary: '', structureSuggestion: '' },
        });
      }
    }
  }, [currentAnswer, currentQuestion, questionNumber, pairs, sessionId, callCoach, navigate]);

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleContinue();
    }
  };

  // ---- Skip (bypass coach entirely) ------------------------------

  const handleSkip = () => {
    navigate('/compose');
  };

  // ---- Begin writing after summary -------------------------------

  const handleBeginWriting = () => {
    navigate('/compose', {
      state: {
        sessionId,
        intentSummary,
        structureSuggestion: suggestion,
      },
    });
  };

  // ---- Render ----------------------------------------------------

  const isAnswerable = phase === 'answering' && currentAnswer.trim().length > 0;

  return (
    <div className="coach-page desk-bg">

      {/* ---- Question flow ---- */}
      {phase !== 'summary' && (
        <div className="coach-card">

          {/* Step dots */}
          <div className="coach-steps" aria-label={`Question ${questionNumber} of 3`}>
            {[1, 2, 3].map((n) => (
              <div
                key={n}
                className={[
                  'coach-step-dot',
                  n === questionNumber ? 'coach-step-dot--active' : '',
                  n < questionNumber   ? 'coach-step-dot--done'   : '',
                ].filter(Boolean).join(' ')}
              />
            ))}
          </div>

          {/* Loading first question */}
          {phase === 'loading' && (
            <div className="coach-loading">
              <span>A moment</span>
              <span className="coach-loading-dots" aria-hidden="true">
                <span /><span /><span />
              </span>
            </div>
          )}

          {/* Error state */}
          {phase === 'error' && (
            <>
              <p className="coach-error">{apiError}</p>
              <div className="coach-actions coach-actions--visible">
                <div />
                <button className="coach-btn-skip" onClick={handleSkip}>
                  Skip and write now
                </button>
              </div>
            </>
          )}

          {/* Question reveal */}
          {(phase === 'question' || phase === 'answering' || phase === 'next-loading') && (
            <>
              <div className="coach-question-wrap">
                <p className="coach-question" aria-live="polite">
                  {questionReveal.displayed}
                  <span
                    className={`coach-question-cursor ${questionReveal.done ? 'coach-question-cursor--hidden' : ''}`}
                    aria-hidden="true"
                  />
                </p>
              </div>

              {/* Answer area — fades in once question is fully revealed */}
              <div
                className={`coach-answer-wrap ${phase === 'answering' ? 'coach-answer-wrap--visible' : ''}`}
              >
                <textarea
                  ref={answerRef}
                  className="coach-answer"
                  value={currentAnswer}
                  onChange={(e) => setCurrentAnswer(e.target.value)}
                  onKeyDown={handleKeyDown}
                  placeholder="Type your answer… (Enter to continue)"
                  rows={3}
                  disabled={phase !== 'answering'}
                  aria-label={`Answer to question ${questionNumber}`}
                />
              </div>

              {/* Actions */}
              <div
                className={`coach-actions ${phase === 'answering' ? 'coach-actions--visible' : ''}`}
              >
                <button
                  className="coach-btn-continue"
                  onClick={handleContinue}
                  disabled={!isAnswerable}
                >
                  {phase === 'next-loading'
                    ? 'One moment…'
                    : questionNumber < 3 ? 'Continue →' : 'Done →'}
                </button>

                <button className="coach-btn-skip" onClick={handleSkip}>
                  Skip the ritual
                </button>
              </div>
            </>
          )}
        </div>
      )}

      {/* ---- Summary screen ---- */}
      {phase === 'summary' && (
        <div className="coach-summary">
          <p className="coach-summary-eyebrow">Before you begin</p>

          <p className="coach-summary-intent" aria-live="polite">
            {summaryReveal.displayed}
            <span
              className={`coach-question-cursor ${summaryReveal.done ? 'coach-question-cursor--hidden' : ''}`}
              aria-hidden="true"
            />
          </p>

          {summaryReveal.done && suggestion && (
            <>
              <div className="coach-summary-divider" aria-hidden="true" />
              <p className="coach-summary-suggestion" aria-live="polite">
                {suggestReveal.displayed}
                <span
                  className={`coach-question-cursor ${suggestReveal.done ? 'coach-question-cursor--hidden' : ''}`}
                  aria-hidden="true"
                />
              </p>
            </>
          )}

          <div className="coach-summary-actions">
            <button
              className="coach-btn-begin"
              onClick={handleBeginWriting}
              disabled={!summaryReveal.done}
            >
              Begin Writing
            </button>

            <button className="coach-btn-skip" onClick={handleSkip}>
              Skip this
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
